#!/bin/bash
source /etc/profile

###################开始基础镜像脚本修改##########################

#由于这个容器是以heaven用户来启动，因此docker run -e 后面的变量是传递给heaven用户的，2而run_soft.sh中的sudo命令是以root用户执行，所以sudo没有-e传递的变量,这点以后需要注意
#如果容器不能正常运行，注意检查下变量，以及基础镜像里需要的变量


#修改来自registry.cn-hangzhou.aliyuncs.com/sourcegarden/docker-ocserv-ofss:v1.0中的run_soft.sh文件
#ocserv和x2go结合有问题,使用ocserv则x2go无法显示桌面
sudo sed -i.bak '/run_ocserv$/d' /start_soft.sh

#删除run_soft.sh 中的tail -f /var/log/squid/access.log命令
sudo sed -i.bak '/access.log/d' /start_soft.sh

#修改来自registry.cn-hangzhou.aliyuncs.com/sourcegarden/docker-ocserv-ofss:v1.0中的/etc/frp/frpc_full.ini文件
#frpc配置文件中的ocserv段虽然用不上,但是先保留这
#frpc配置文件中的novnc段可用不用配,直接用squid做代理来访问也可以,这里先加上
# sudo chown heaven:heaven /etc/frp/frpc_full.ini
cat >> /etc/frp/frpc_full.ini << EOF
[range:novnc ${hostname_in_docker}]
type = tcp
local_ip = 127.0.0.1
local_port = 6080
remote_port = 0
use_encryption = false
use_compression = false
EOF
# sudo chown root:root /etc/frp/frpc_full.ini
bash -x /start_soft.sh
###################结束基础镜像脚本修改##########################

mkdir -p "$HOME/.x11vnc"
PASSWD_PATH="$HOME/.x11vnc/passwd"

x11vnc -storepasswd $VNC_PASSWD $PASSWD_PATH
chmod 600 $PASSWD_PATH

$NOVNC_HOME/utils/launch.sh --vnc localhost:$VNC_PORT --listen $NOVNC_PORT &
Xvfb $DISPLAY -screen 0 "$VNC_RESOLUTION"x"$VNC_COL_DEPTH" &
startxfce4 --replace > $HOME/wm.log 2>&1 &
sleep 1
x11vnc -xkb -noxrecord -noxfixes -noxdamage -permitfiletransfer -tightfilexfer -rfbauth $PASSWD_PATH -display $DISPLAY -forever -o $HOME/.x11vnc/x11vnc.log -bg && tail -f $HOME/.x11vnc/x11vnc.log